FribergCarRental/Controllers/AdminCarController.cs
using FribergCarRental.Data;
using FribergCarRental.Data.interfaces;
using FribergCarRental.Models;
using FribergCarRental.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FribergCarRental.Controllers
{
    public class AdminCarController : AdminCheckBaseController
    {
        private readonly ICarRepository _carRepository;
        private readonly IRentalRepository _rentalRepository;

        public AdminCarController(ICarRepository carRepository, IRentalRepository rentalRepository)
        {
            this._carRepository = carRepository;
            this._rentalRepository = rentalRepository;
        }
        // GET: AdminCarController
        public async Task<IActionResult> Index()
        {
            var cars = await _carRepository.GetAllAsync();
            return View(cars);
        }

        // GET: AdminCarController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var car = await _carRepository.GetByIdAsync(id);
            return View(car);
        }

        // GET: AdminCarController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var car = await _carRepository.GetFullByIdAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // GET: AdminCarController/Create
        public IActionResult Create()
        {
            return View();
        }

        // GET: AdminCarController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var car = await _carRepository.GetByIdAsync(id);
            if(car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: AdminCarController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCarViewModel createCarVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var car = new Car
                    {
                        Model = createCarVM.Model,
                        Year = createCarVM.Year,
                        Price = createCarVM.Price,
                        Description = createCarVM.Description,
                        IsActive = true,

                        Images = new List<Image>()
                        {
                            new Image { ImageUrl = createCarVM.ImageUrl }
                        }
                    };
                    await _carRepository.AddAsync(car);

                    TempData["SuccessMessage"] = $"{car.Model} har lagts till!";
                    return RedirectToAction("Index");
                }
                return View(createCarVM);

            }
            catch
            {
                return View();
            }
        }

        // POST: AdminCarController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Car carModel, string? NewImageUrl)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var car = await _carRepository.GetFullByIdAsync(carModel.Id);
                    if (car == null)
                    {
                        return NotFound();
                    }

                    car.Model = carModel.Model;
                    car.Year = carModel.Year;
                    car.Price = carModel.Price;
                    car.Description = carModel.Description;
                    car.IsActive = carModel.IsActive;

                    var imageToRemove = new List<Image>();

                    for (int i = 0; i < car.Images.Count; i++)
                    {
                        var updatedUrl = carModel.Images[i].ImageUrl;

                        if(string.IsNullOrEmpty(updatedUrl))
                        {
                            imageToRemove.Add(car.Images[i]);
                        }
                        else
                        {
                            car.Images[i].ImageUrl = updatedUrl;
                        }
                    }

                    foreach (var image in imageToRemove)
                    {
                        await _carRepository.RemoveImageAsync(image.Id);
                    }

                    if (!string.IsNullOrEmpty(NewImageUrl))
                    {
                        car.Images.Add(new Image { ImageUrl = NewImageUrl });
                    }

                    await _carRepository.UpdateAsync(car);
                    TempData["SuccessMessage"] = $"Bil: {car.Model} har uppdaterats!";
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View(carModel);
            }
            
        }

        // POST: AdminCarController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Car car)
        {
            try
            {                
                var carToDisable = await _carRepository.GetByIdAsync(car.Id);
                if (carToDisable != null)
                {
                    await _carRepository.DisableAsync(carToDisable);
                    TempData["SuccessMessage"] = $"Bil: {carToDisable.Model} har ändrat status!";
                    return RedirectToAction("Index");
                }
                return NotFound();
            }
            catch
            {
                return View();
            }
        }
    }
}

FribergCarRental/Controllers/CarController.cs
using FribergCarRental.Data.interfaces;
using FribergCarRental.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FribergCarRental.Controllers
{
    public class CarController : Controller
    {
        private readonly ICarRepository _carRepository;

        public CarController(ICarRepository carRepository)
        {
            this._carRepository = carRepository;
        }
        // GET: CarController
        public async Task<IActionResult> Index()
        {
            var cars = await _carRepository.GetAllAsync();
            if (cars != null)
            {
                return View(cars);
            }
            return View();
        }

        public IActionResult RentCar(int carId)
        {
            if (HttpContext.Session.GetString("UserId") == null || HttpContext.Session.GetString("UserRole") == "Admin")
            {
                TempData["SuccessMessage"] = $"Logga in eller skapa konto för att boka en bil!";

                var returnUrl = Url.Action("SelectDates", "Rental");
                return RedirectToAction("Login", "Account", new { returnUrl });
            }

            return RedirectToAction("SelectDates", "Rental");
        }

        // GET: CarController/Details/5
        public async Task<IActionResult> Details(int id, DateOnly startDate, DateOnly endDate)
        {
            var car = await _carRepository.GetFullByIdAsync(id);
            ViewData["StartDate"] = startDate;
            ViewData["EndDate"] = endDate;

            return View(car);
        }
    }
}

FribergCarRental/Views/Shared/_DeleteCard.cshtml
@model Dictionary<string, object>

<div class="card p-4">
    <h4 class="card-header mb-3 text-center">@ViewData["Title"]</h4>

    @foreach (var detail in Model)
    {
        <div class="mb-3">
            <strong>@detail.Key:</strong> @detail.Value
        </div>
    }

    <div class="d-flex justify-content-between mt-4">
        @if (ViewData["DeleteAction"] != null)
        {
            if (ViewData["Aktivera"] != null)
            {
                <form asp-action="@ViewData["DeleteAction"]" method="post">
                    <input type="hidden" name="UserId" value="@ViewData["ItemId"]" />
                    <input type="submit" value="@ViewData["Aktivera"]" class="btn btn-danger" />
                </form>
            }
            else if (ViewData["Inaktivera"] != null)
            {
                <form asp-action="@ViewData["DeleteAction"]" method="post">
                    <input type="hidden" name="UserId" value="@ViewData["ItemId"]" />
                    <input type="submit" value="@ViewData["Inaktivera"]" class="btn btn-danger" />
                </form>
            }
            else
            {
                <form asp-action="@ViewData["DeleteAction"]" method="post">
                    <input type="hidden" name="UserId" value="@ViewData["ItemId"]" />
                    <input type="submit" value="Ta bort" class="btn btn-danger" />
                </form>
            }
        }

        <a asp-action="@ViewData["BackAction"]" class="btn btn-secondary">
            <i class="bi bi-arrow-left"></i> Tillbaka
        </a>
    </div>
</div>

FribergCarRental/Views/Shared/_DetailsCard.cshtml
@model Dictionary<string, object>


<div class="card p-4">
    
    <h4 class="card-header text-black mb-5 text-center">@ViewData["Title"]</h4>

    @foreach (var detail in Model)
    {
        <div class="mb-3">
            <strong>@detail.Key:</strong> @detail.Value
        </div>
    }

    <div class="d-flex justify-content-between mt-4">
        @if (ViewData["EditAction"] != null)
        {
            <a asp-action="@ViewData["EditAction"]" asp-route-id="@ViewData["ItemId"]" class="btn btn-primary">
                <i class="bi bi-pencil"></i> Ändra
            </a>
        }

        <a asp-action="@ViewData["BackAction"]" class="btn btn-secondary">
            <i class="bi bi-arrow-left"></i> Tillbaka
        </a>
    </div>
</div>

FribergCarRental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FribergCarRental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FribergCarRental.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container centered-container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/images/BigLogo.png" width="30" height="30" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Index">Hem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Våra bilar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="RentCar">Boka</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav d-flex justify-content-end">
                        @if (Context.Session.GetString("UserRole") != null)
                        {
                            <li class="nav-item dropdown">
                                <button class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span>Inloggad: @Context.Session.GetString("UserName")</span>
                                </button>
                                <ul class="dropdown-menu ">
                                    @if (Context.Session.GetString("UserRole") == "Admin")
                                    {
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AdminDashboard"><i class="fa-solid fa-house"></i> | Admin Dashboard</a></li>
                                        <li><hr class="dropdown-divider" /></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="AdminAccount" asp-action="Index"><i class="fa-solid fa-users"></i> | Hantera konton</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="AdminCar" asp-action="Index"><i class="fa-solid fa-car"></i> | Hantera bilar</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="AdminRental" asp-action="Index"><i class="fa-regular fa-rectangle-list"></i> | Hantera bokningar</a></li>
                                        <li><hr class="dropdown-divider" /></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-right-from-bracket"></i> | Logga ut</a></li>
                                    }
                                    @if (Context.Session.GetString("UserRole") == "Customer")
                                    {
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Index"><i class="fa-regular fa-rectangle-list"></i> | Mina bokningar</a></li>
                                        <li><hr class="dropdown-divider" /></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-right-from-bracket"></i> | Logga ut</a></li>
                                    }
                                </ul>
                            </li>
                        }
                        @if (Context.Session.GetString("UserRole") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Create">Skapa konto</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container centered-container mt-4">
        <main role="main" class="pb-3">
            @if (TempData["SuccessMessage"] != null)
            {
                <div id="toastContainer" class="toast-container toast-custom">
                    <div id="successToast" class="toast show bg-success text-white" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="toast-header">
                            <strong class="me-auto">Information</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                        <div class="toast-body">
                            @TempData["SuccessMessage"]
                        </div>
                    </div>
                </div>
            }
            @if (TempData["WarningMessage"] != null)
            {
                <div id="toastContainer" class="toast-container toast-custom">
                    <div id="successToast" class="toast show bg-warning text-white" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="toast-header">
                            <strong class="me-auto">Information</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                        <div class="toast-body">
                            @TempData["WarningMessage"]
                        </div>
                    </div>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="bg-light footer text-muted text-center border-top">
        <div class="container centered-container align-items-center">
            &copy; 2025 - Friberg Car Rentals AB 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/login.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/c3adebd6e3.js" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>